### ISSUE TITLE
make[1]: *** [networking/udhcp/d6_dhcpc.o] Error 1

### ISSUE THREAD

**Issue by liwenjie119** [mirror/busybox#15]
networking/udhcp/d6_dhcpc.c: 在函数‘udhcpc6_main’中:
networking/udhcp/d6_dhcpc.c:1783:2: 错误： expected declaration or statement at end of input
  return retval;
  ^~~~~~
scripts/Makefile.build:197: recipe for target 'networking/udhcp/d6_dhcpc.o' failed
make[1]: *** [networking/udhcp/d6_dhcpc.o] Error 1
make[1]: *** 正在等待未完成的任务....
  CC      printutils/lpd.o
  CC      printutils/lpr.o
  AR      miscutils/lib.a
Makefile:743: recipe for target 'networking/udhcp' failed
make: *** [networking/udhcp] Error 2

**Comment by yugun** [comment]
I met same trouble

I solved it by adding closing bracket to next line of return retval

**Comment by liwenjie119** [comment]
> I met same trouble
> 
> I solved it by adding closing bracket to next line of return retval

add } to the end of networking/udhcp/d6_dhcpc.o. This file lacks } after line 1783 return retval;

**Comment by liwenjie119** [comment]
already fixed
