### ISSUE TITLE
Feature Request: nslookup SRV query types

### ISSUE THREAD

**Issue by pmelange** [mirror/busybox#16]
It would be really great if nslookup supoorted the SRV query type.

https://github.com/mirror/busybox/blob/3a0eea0887d72f28d13d329be90fe4082cbbd427/networking/nslookup.c#L273-L288

This will be especially useful for openwrt and specifically freifunk-berlin.

**Comment by 111andre111** [comment]
Hi folks, are there any news on this topic?

**Comment by pmelange** [comment]
It's integrated with commit 6b49601
closing

**Comment by 111andre111** [comment]
@pmelange Ah ok. But what busy box version this one is contained? I had a 1.31.1 and there is still no srv record type possible

**Comment by pmelange** [comment]
![Screenshot_2021-08-01_16-44-58](https://user-images.githubusercontent.com/20710446/127775109-ff250a1f-6481-4fca-a2f8-1cd3578679ee.png)

It's in version 1.32.0, 1.32.1, 1.33.0, 1.33.1

**Comment by 111andre111** [comment]
Ok, cool. Nice and thank you. 👍
