### ISSUE TITLE
Feature Request: Wireless tools

### ISSUE THREAD

**Issue by geonaumov** [mirror/busybox#17]
Can you please embed wifi-tools and especially wpa_supplicant that uses the internal SSL library. wifi-tools are easy to build but wpa_supplicant is a nightmare. It will be nice to have them out of the box.

**Comment by protonesso** [comment]
It's a mirror use busybox mailing list. LFS has instructions to build wpa_supplicant. If you don't like it use wsupp or iwd

**Comment by geonaumov** [comment]
I will dig wsupp and iwd. wpa_supplicant requires gnutls, libnl etc. (not sure if this is because of musl + LibreSSL), this is why I don't like it. Thanks for your answer.
