### ISSUE TITLE
Full gnu utilities

### ISSUE THREAD

**Issue by ilobilo** [mirror/busybox#38]
Why won't busybox include full gnu programs instead of their own ones?
![Screenshot_2021-03-23-10-45-32-709_com termux](https://user-images.githubusercontent.com/68286835/112104691-f37f7700-8bc4-11eb-92cf-ed7667148d8f.jpg)

**Comment by stokito** [comment]
BB is a clone of most popular GNU utilities with only most needed functions. It's used on embedded devices where space is limited.
